name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://postgres:postgres@localhost/test_database

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_database
        ports:
          - 5432:5432
        # サービスコンテナが起動するのを待つためのオプション
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      # Rust toolchainのセットアップ
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # sqlx-cliのインストール
      - name: Install sqlx CLI
        run: cargo install sqlx-cli --no-default-features --features postgres

      # データベースの作成
      - name: Create Database
        run: sqlx db create

      # データベースマイグレーション
      - name: Migrate Database
        run: sqlx migrate run

      # ビルド
      - name: Build
        run: cargo build --verbose

      # テストの実行
      - name: Run tests
        run: cargo test --verbose
