name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  issue_comment:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: github.event_name != 'issue_comment'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose

  test:
    if: >
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request != '' &&
      contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test --verbose
